### ISSUE TITLE
build gradle files are giving errors and the app is not building

### ISSUE THREAD

**Issue by shipsywor** [kuaddo/Tsuidezake-Android#129]
build gradle files are giving errors, that's why the app is not compiling.

![26](https://user-images.githubusercontent.com/67386890/116045688-3beef080-a6ad-11eb-8d56-0bbc143bac8b.png)

**Steps to reproduce**

1. Clone this project.
2. Open this project in Android Studio.
3. Notice error while trying to build the app.

**Comment by shiita0903** [comment]
@shipsywor 
Sorry, this repository is public but several parts are hidden intendedly. I'm not going to support building the app.
